from typing import Callable, Protocol

from tiles_survive_automation.input.models import RawEvent


class InputRecorder(Protocol):
    def start(self, on_event: Callable[[RawEvent], None]) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...


class InputController(Protocol):
    def click(self, x: int, y: int, button: str = "left") -> None: ...
    def double_click(self, x: int, y: int) -> None: ...
    def drag(self, from_x: int, from_y: int, to_x: int, to_y: int,
              duration_ms: int) -> None: ...
    def scroll(self, x: int, y: int, delta: int) -> None: ...
    def key_press(self, key: str) -> None: ...
    def hotkey(self, keys: list[str]) -> None: ...
    def release_all(self) -> None: ...


class ManualClickWatcher(Protocol):
    """Detects a real (human) left-mouse-button-down, ignoring the app's
    own synthetic clicks -- used to let the user reclaim control from a
    running Rule/Schedule by clicking, instead of only via the F9 hotkey.
    """

    def start(self, on_manual_click: Callable[[], None]) -> None: ...
    def stop(self) -> None: ...
